name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # Her gün gece 00:00'da çalışır
  workflow_dispatch: # Manuel çalıştırma imkanı

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bağımlılıkları kur
        run: pip install requests

      - name: WakaTime verilerini çek ve kaydet
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          import requests, json, os

          api_key = os.getenv("WAKATIME_API_KEY")
          headers = {"Authorization": f"Bearer {api_key}"}

          # all_time yerine last_7_days ile test et, sonra all_time'a geçebilirsin
          url = "https://wakatime.com/api/v1/users/current/stats/all_time"

          r = requests.get(url, headers=headers)
          if r.status_code == 200:
              data = r.json()
              # public klasörünün var olduğundan emin ol
              import os
              os.makedirs("public", exist_ok=True)
              with open("public/wakatime.json", "w", encoding="utf-8") as f:
                  json.dump(data, f, ensure_ascii=False, indent=2)
              print("✅ WakaTime verileri kaydedildi.")
          else:
              print(f"❌ Hata: {r.status_code} - {r.text}")

      - name: Commit ve push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/wakatime.json
          git commit -m "Update WakaTime stats" || echo "No changes to commit"
          git push
